# Package Overview

package_name: shopeepy_wrapped

# Login Config

LOGINPAGE_LINK: https://shopee.ph/buyer/login

USERNAME_INPUT:
  element_tag: input
  attribute: name
  attribute_value:
    - loginKey

PASSWORD_INPUT:
  element_tag: input
  attribute: name
  attribute_value:
    - password

LOGIN_BUTTON:
  element_tag: button
  attribute: class
  attribute_value:
    - wyhvVD _1EApiB hq6WM5 L-VL8Q cepDQ1 _7w24N1

VERIFY_BY_EMAIL_LINK: //div[text()='Verify by Email Link']

WRONG_CREDENTIALS:
  element_tag: div
  attribute: class
  attribute_value:
    - gCY-Ye

LOGIN_CONFIRM:
  element_tag: div
  attribute: class
  attribute_value:
    - navbar__username

# Scrape Config

PURCHASEPAGE_LINK: https://shopee.ph/user/purchase/

PURCHASES:
  element_tag: div
  attribute: class
  attribute_value:
    - _6nAGBW

NAME:
  element_tag: span
  attribute: class
  attribute_value:
    - WVc4Oc

PRICE:
  element_tag: span
  attribute: class
  attribute_value:
    - ghw9hb
    - ghw9hb igidiy

STORE:
  element_tag: div
  attribute: class
  attribute_value:
    - mzsqa6

STATUS:
  element_tag: div
  attribute: class
  attribute_value:
    - l4WFo0

HREF:
  element_tag: a

BUNDLE:
  element_tag: span
  attribute: class
  attribute_value:
    - vdofqJ

PRODUCT:
  element_tag: a
  attribute: class
  attribute_value:
    - QkIuzE

BREAD_CRUMB_ELEMENT:
  element_tag: div
  attribute: class
  attribute_value:
    - flex items-center RnKf-X page-product__breadcrumb

BREAD_CRUMB:
  element_tag: a
  attribute: class
  attribute_value:
    - akCPfg

USER_PURCHASE_STR: /user/purchase/order/

ORDER_ID:
  element_tag: span

ORDER_DETAILS:
  element_tag: div
  attribute: class
  attribute_value:
    - Zrxery

ORDER_DETAILS_ELEMENTS:
  element_tag: span
  attribute: class
  attribute_value:
    - -XHRLL

THUMBNAIL:
  element_tag: div
  attribute: class
  attribute_value:
    - shopee-image__content

TRACKING_STAGES:
  element_tag: div
  attribute: class
  attribute_value:
    - stepper__step-text

TRACKING_TIMESTAMPS:
  element_tag: div
  attribute: class
  attribute_value:
    - stepper__step-date

PRICE_BREAKDOWN_ELEMENT:
  element_tag: div
  attribute: class
  attribute_value:
    - MqHNeD

PRICE_BREAKDOWN_CATEGORIES:
  element_tag: div
  attribute: class
  attribute_value:
    - vXeTuK

PRICE_BREAKDOWN_VALUES:
  element_tag: div
  attribute: class
  attribute_value:
    - _30Hj4X

# Data Cleaning Config

ORDERS_KEEP_COLS:
  - order_status
  - order_id
  - order_placed
  - order_paid
  - order_shipped_out
  - order_received
  - order_completed
  - merchandise_subtotal
  - shipping_fee
  - shipping_discount_subtotal
  - order_total
  - payment_method
  - order_cancelled
  - redeemed_shopee_coins
  - shopee_voucher_applied
  - shopee_coins_earned
  - shop_voucher_applied
  - return_refund_accepted
